Cloudrun as the scheduler[WIP]
rakutentech/shibuya pull request #21
Opened 2021-01-18 06:10 UTC by iandyh

1. Add Cloudrun as scheduler
2. k8s and cloudrun are wrapped into an interface
3. need to make shibuya-agent to emit the stdout of the jmeter(k8s has native support)

Although it's marked as WIP, but it should be all done. Should be ok for review. We might need to think about how we manage the config for local, I will address in this PR later.

2021-01-21 12:51 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +	rs, err := run.NewService(ctx, option.WithEndpoint(cfg.APIEndpoint))
Why do we need to provide APIEndoint here?

2021-01-21 12:55 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +func (cr *CloudRun) startWriteRequestWorker() {
Why do we need to queue these actions in CloudRun? It can't handle many requests?

2021-01-21 12:57 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +			counter += 2
Why is it +2 for create?

2021-01-21 13:01 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +func (cr *CloudRun) createService(projectID, collectionID, planID int64, engineID int, executorConfig *config.ExecutorContainer) error {
`makeService` and `createService` are very confusing

2021-01-21 13:19 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +			EnginesReachable: hasEnginesDeployed,
This is PlanStatus and we cannot use the value of `len(items)>0` here for EnginesReachable since the `len(items)` is for engines in the entire collection. So it's possible this particular plan has 0 engines deployed while other plan has all of it's engines deployed.

2021-01-21 13:25 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +			EnginesReachable: hasEnginesDeployed,
I see we are already calculating the true reachability in Line 253, so we can start with a `true` here directly rather than using `hasEnginesDeployed`

2021-01-21 13:30 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +	// need to make it get url by plan
Can you explain a bit more on this comment? What does it mean?

2021-01-21 13:36 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +	return len(items)
This isn't checking if they are ready or not, it's just deployment count

2021-01-21 13:40 UTC, harpratap commented on shibuya/engines/jmeter/shibuya-agent.go
> +		log.Printf("shibuya-agent: Shutdown is f finished, resetting pid to zero")
Typo?

2021-01-21 13:45 UTC, harpratap commented on shibuya/engines/jmeter/shibuya-agent.go
> +	log.SetOutput(mw)
So how do we debug in case of fatal crash? Can this still keep a history of output when engines goes down and we do `kubectl logs engine-xxx --previous` ?

2021-01-21 13:52 UTC, harpratap commented on shibuya/scheduler/meta.go
> +func makeIngressName(projectID, collectionID, planID int64, engineID int) string {
All the ingress related part is only needed in K8s and not in Cloud Run, so it should be moved to k8s.go?

2021-01-21 13:53 UTC, harpratap commented on shibuya/scheduler/types.go
> +	DeployIngressController(ProjectID, collectionID int64) error
Ingress is just an implementation detail of K8s, we don't need it for all schedulers.

2021-01-21 14:00 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +	cr.httpClient = &http.Client{
If we add a proxy here we can potentially use most of Shibuya without needing proxy in the env vars even for google cloud?

2021-01-21 14:00 UTC, harpratap reviewed
Will take a look at remaining changes soon

2021-01-21 23:57 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +	rs, err := run.NewService(ctx, option.WithEndpoint(cfg.APIEndpoint))
Because its API is not well supported yet. https://cloud.google.com/run/docs/reference/rest

Actually, I feel like I might be the only one in the internet to make the API work. There are so many quirks on using it.

2021-01-22 00:10 UTC, iandyh commented on shibuya/scheduler/types.go
> +	DeployIngressController(ProjectID, collectionID int64) error
As long as k8s needs it, we need to have it there? Although the term is in k8s, but the requirement is there for every other scheduler as you will need some ingress component there(Proxy essentially). In this case, cloud run has build-in support.

2021-01-22 00:13 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +func (cr *CloudRun) startWriteRequestWorker() {
yes, we have quota limit there. I've already requested the raise. now Read: 6000, write: 600. In case of Write, although the number is high, we probably never need it because when there is a large deployment, the bottleneck will not be at the api anyway.

2021-01-22 00:13 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +			counter += 2
Added some comments.

2021-01-22 00:14 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +func (cr *CloudRun) createService(projectID, collectionID, planID int64, engineID int, executorConfig *config.ExecutorContainer) error {
renamed the `createService` func.

2021-01-22 00:16 UTC, iandyh commented on shibuya/engines/jmeter/shibuya-agent.go
> +	log.SetOutput(mw)
No. The logs from this api go away if the pod is down. You should be able to find the logs in the GCP dashboard. Will share how to do it later.

2021-01-22 00:59 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +			EnginesReachable: hasEnginesDeployed,
It's a bit tricky to understand this bit of code. I've added some comments.

2021-01-22 02:09 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +	// need to make it get url by plan
Yes, I added more comments. It's used by `generateEnginesByUrl`

2021-01-22 02:11 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +	return len(items)
Yes, actually, what we want is deployment count, but in the past we were using ready pods. I'll address this later. Currently flag it as TODO.

2021-01-22 02:12 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +	cr.httpClient = &http.Client{
Yes, i think now it's still using the env vars. let me add that.

2021-01-22 06:49 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +	cr.httpClient = &http.Client{
now it will use the `HTTPProxyClient`

2021-01-22 07:36 UTC, harpratap commented on shibuya/engines/jmeter/shibuya-agent.go
> +	log.SetOutput(mw)
@iandyh That will be in GCP, but how about vanilla K8s?

2021-01-22 07:37 UTC, harpratap commented on shibuya/scheduler/types.go
> +	DeployIngressController(ProjectID, collectionID int64) error
@iandyh In that case it should be a very generic term like `ExposeCollection` instead of ingress controller

2021-01-22 07:52 UTC, harpratap commented on .gitignore
> +shibuya/config.json
Am I missing something? Where is the config.json supposed to go? No changes in Dockerfile either

2021-01-23 14:38 UTC, harpratap requested changes
1. The config.json is missing changes, it will break things if relevant bits are not updated
2. We should remove all the dependencies in `controller` on `scheduler`, the ingress-controller thing should be somehow hidden inside k8s.go

2021-01-23 14:38 UTC, harpratap commented on shibuya/controller/engine.go
> +	for i, e := range engines {
This is very dangerous. The implementation inside scheduler should not interfere with controller, could be easily overlooked when adding/removing new schedulers

2021-01-23 14:38 UTC, harpratap commented on shibuya/controller/main.go
> +	if c.needIngress() {
We should remove this dependency on controller to decide if ingress is needed or not and just let scheduler do it.

2021-01-23 14:38 UTC, harpratap commented on shibuya/controller/main.go
> +	if c.schedulerKind != "cloudrun" {
We need to add new error type `NotImplemented` or `FeatureUnavailable` , and `fetchEngineMetrics()` needs to simply exit if it sees that error

2021-01-23 14:38 UTC, harpratap commented on shibuya/scheduler/cloudrun.go
> +	name := fmt.Sprintf("projects/%s/locations/%s/services/%s", cr.projectID, "asia-northeast1", svc.Metadata.Name)
Can you add comments here why we need this `iamPolicy` and `bindings`? And what does "asia-northeast1" here mean? Will it always launch engines in Tokyo region?

2021-01-25 00:39 UTC, iandyh commented on shibuya/scheduler/cloudrun.go
> +	name := fmt.Sprintf("projects/%s/locations/%s/services/%s", cr.projectID, "asia-northeast1", svc.Metadata.Name)
I add some comments. This is a good catch, as I hard coded in the code. Now it's provided as a config.

2021-01-25 00:39 UTC, iandyh commented on shibuya/controller/main.go
> +	if c.schedulerKind != "cloudrun" {
Done

2021-01-25 00:39 UTC, iandyh commented on shibuya/controller/main.go
> +	if c.needIngress() {
Done.

2021-01-25 00:39 UTC, iandyh commented on shibuya/controller/engine.go
> +	for i, e := range engines {
Done.

2021-01-25 00:39 UTC, iandyh commented on shibuya/controller/engine.go
> +	if !strings.Contains(be.engineUrl, "http") {
Put this into a func.

2021-01-25 00:40 UTC, iandyh commented on shibuya/controller/collection.go
> +	return c.Scheduler.PurgeCollection(collection.ID)
I deliberately removed the retry here(Because quota constraints). As users can do the retry.

2021-01-25 00:40 UTC, iandyh commented on .gitignore
> +shibuya/config.json
Done.

2021-01-25 00:40 UTC, iandyh commented on shibuya/scheduler/types.go
> +	DeployIngressController(ProjectID, collectionID int64) error
Done.

2021-01-25 00:41 UTC, iandyh commented on shibuya/scheduler/meta.go
> +func makeIngressName(projectID, collectionID, planID int64, engineID int) string {
I think it's ok as `Ingress` a neutral name.

2021-01-25 00:57 UTC, harpratap commented on makefile
> +	cp shibuya/config_tmpl.json shibuya/config.json
The reason we wanted `config_tmpl.json` was because we want to change the config without needing to put into git. But now that `config_tmpl.json` will always override `config.json` we need to make changes to the template everytime. So it changes nothing from previous behaviour

2021-01-25 02:21 UTC, iandyh commented on makefile
> +	cp shibuya/config_tmpl.json shibuya/config.json
Yes, I will need to address this later. Ideally, we need to have something like config_generator.

2021-01-25 03:29 UTC, harpratap commented on shibuya/controller/engine.go
> +	for i, e := range engines {
@iandyh I am still confused as to why we even need that if-else in `updateEngineUrl()`. `FetchEnginesUrlsByPlan()` should give us the final url of engines that we can directly call to, we shouldn't need to do any switch based on scheduler behavior in controller

2021-01-25 03:30 UTC, harpratap reviewed
Need some clarification about confusing parts

2021-01-25 03:32 UTC, harpratap commented on makefile
> +	cp shibuya/config_tmpl.json shibuya/config.json
@iandyh I think it's an overkill for such a simple config.json, we don't need generators or any fancy logic for this. A simple copy-paste and `git checkout` is enough for our workflow

2021-01-25 12:25 UTC, iandyh commented on shibuya/controller/engine.go
> +	for i, e := range engines {
Right now because in k8s, we only return the url with the collection so the controller will still need to gen the url with the engine svc name. We could consider directly return the url so the controller does not need to do anything. But it will be out of scope of this PR.

Because above, controller needs to do it with an if. Although directly `fmt.Sprintf` should work as the svc name is an emtpy string anyway, but I want to keep things clear.

2021-01-26 04:49 UTC, harpratap approved these changes

2021-01-27 01:30 UTC, merged